### ISSUE TITLE
Stone cards

### ISSUE THREAD

**Issue by copypasta1** [itrend/balcal#11]
Three of a kind with two stone cards is being calculated as a full house
EX 999SS, 999ss, 99900 should be a three of a kind

**Comment by itrend** [comment]
🤦‍♂️ thanks for the report, it's fixed now

btw, do you know what happens if you play five stone cards? is it still a high card or something else?

**Comment by copypasta1** [comment]
5 Stone is just high card. I wondered myself until I saw it be played
